baseURL = 'http://example.org/'
languageCode = 'pt-br'
title = 'New Relic - Parceiro Gameday!'
# Change the default theme to be use when building the site with Hugo
theme = "hugo-theme-learn-master"

# For search functionality
[outputs]
home = [ "HTML", "RSS", "JSON"]

[params]
  # Change default color scheme with a variant one. Can be "red", "blue", "green".
  themeVariant = "blue"
